### ISSUE TITLE
New version completely breaks my system - definitely not a minor version bump

### ISSUE THREAD

**Issue by AntJanus** [grevory/angular-local-storage#289] opened 2016-02-22 17:07 UTC
From the looks of the minor version bump, one would think that only minor updates were done but when I checked out the commit history, I saw that the entire module was changed. Including a commit: https://github.com/grevory/angular-local-storage/commit/8a738f918e2407640dfe0f57ad01851b16d33cb2 that features over 900 line code additions and 800 lines of code deletions. (difference between versions for reference: https://github.com/grevory/angular-local-storage/compare/0.2.3...0.2.4)

Is there a way you guys can bump this a major version? The update broke all of my tests and functionality across my application since I was using the `~` for versioning (meaning, it can pull in minor version changes). 

Just for reference:

I'm using Browserify + Babel to compile my code and was using `angular-local-storage` via browserify-shim over Bower.

**Comment by StavroMueller** [comment] 2016-02-22 17:25
I work with @AntJanus, and just for future reference if anyone tries to search for this specific problem, the top-level error we were getting in our tests was `Error: Cannot find module 'angular'`.

**Comment by ealves-pt** [comment] 2016-02-22 20:08
Issue caused by the same change that affect #288. I will revert that change and create a new tag.

**Comment by AntJanus** [comment] 2016-02-22 22:49
@ealves-pt thanks!

**Comment by ealves-pt** [comment] 2016-02-23 09:20
@grevory can you publish version 0.2.5 to NPM? I have already created the tag for it.

**Comment by ealves-pt** [comment] 2016-02-23 09:21
This should be fixed with PR #291. I will wait for some feedback to see if it's possible to close this issue.

**Comment by grevory** [comment] 2016-02-23 14:47
I think his point, other than the bug, was that it was a major change and we gave it a patch version.

[major].[minor].[patch]

How do we change the versioning for a release?

**Comment by eddiemonge** [comment] 2016-02-23 19:28
a patch release that reverts the big change should be done then a new major release with all the current changes

**Comment by AntJanus** [comment] 2016-02-23 20:10
Thanks guys! I feel like I came on a little strong so I want to apologize, I had a stressful day.

I was thinking that semver would make a lot of sense especially since both bower and NPM default to updating patches automatically rather than locking you down to a version. If that makes sense.

**Comment by ealves-pt** [comment] 2016-02-23 21:41
Yeah we should be using semver. I didn't expected those changes would have such a huge impact otherwise I would have bumped the major version.

@eddiemonge yeah, the patch is done and I hope everything is fixed. Then that will be released as a major, together with other breaking change functionalities that have a PR open at the moment.

**Closed** 2016-02-24 07:24 UTC
Labels: bug
