### ISSUE TITLE
setPrefix in localStorageService, so we can switch prefix during execution

### ISSUE THREAD

**Issue by lorenzyannick** [grevory/angular-local-storage#176] opened 2014-12-07 22:05 UTC
Provide method to set prefix after config

// angular-local-storage.js
var getPrefix = function() {
 return prefix;
}

var setPrefix = function(val) {
 prefix = val;

 // DUPLICATE CODE line 104 => put in a function ?
 // If there is a prefix set in the config lets use that with an appended period for readability
    if (prefix.substr(-1) !== '.') {
      prefix = !!prefix ? prefix + '.' : '';
    }

}

return {
                 getPrefix: getPrefix,
                 setPrefix: setPrefix,
                 isSupported: browserSupportsLocalStorage,

// TEST in app.js //
console.log("localStorageService prefix");
console.log(localStorageService.getPrefix());
localStorageService.setPrefix("mynewprefix");
console.log(localStorageService.getPrefix());

**Comment by moradology** [comment] 2015-01-12 16:14
I disagree that the need for namespacing implies anything about third party code. Consider the inclusion of modules in angular and the fact that it is generally thought to be best practice to use highly granular spaces.

It just seems neater to me that, e.g., my UserPreferences service, namespaced in angular-land as 'app.user.pref' should also namespace its localstorage entries in such a way as to ensure  that other services can't so easily cause collisions.

**Comment by ChicagoDave** [comment] 2015-01-12 23:27
I have a use-case that needs setPrefix in the service. In an internal organization where als is embedded in another library for hybrid mobile apps, we don't want the app developer to determine the prefix, we want this embedded in our library and based on other configuration data.

If we leave it as is, an app developer could ignore the setPrefix requirement and in a clearAll(), wipe out all mobile app local storage...something we absolutely do not want to have happen.

So the issue is, assume this library is shared by many applications in the same environment. Not one application in one environment.

**Comment by lorenzyannick** [comment] 2015-01-13 06:59
To explain my case, in the mobile app we can change from one environnement to another du ring exécution time with somes params & data
The case is to change prefix according to the env variable
Maybe there is another way to do it ?

**Comment by ChicagoDave** [comment] 2015-01-13 17:14
I've tested a change I think makes sense.

var changePrefix = function(localStoragePrefix) {
    prefix = localStoragePrefix;
};

and then add 'changePrefix: changePrefix' to the list of returned functions.

It's differentiated from setPrefix, which is a configuration function, but allows more complex local storage handling without forcing the developer to manage app-level keys.

**Comment by thoughtpalette** [comment] 2015-01-13 17:19
+1 @ChicagoDave

**Comment by lorenzyannick** [comment] 2015-01-13 22:49
Why not changePrefix instead of setPrefix (config function)
An idea : remember all the prefixes used (in array) and add a clearAllPrefixesStuff function to really clear all datas ?

**Comment by episodeyang** [comment] 2015-11-02 00:19
Is there any update on this issue? We need to dynamically change the prefix in our app as well.

**Comment by portus84** [comment] 2017-06-01 18:35
+1

**Comment by portus84** [comment] 2017-06-19 20:05
Some news?

**Comment by grevory** [comment] 2017-06-21 13:03
Last night I merged #186.

**Closed** 2017-06-21 13:03 UTC
Labels: enhancement, pr-needs-feedback

**Comment by lorenzyannick** [comment] 2017-06-21 13:34
Thx a lot
