### ISSUE TITLE
Setting storage type based on compatibility

### ISSUE THREAD

**Issue by g2graman** [grevory/angular-local-storage#281] opened 2016-02-16 02:39 UTC
Is it possible in an angular config block to check whether the current storagetype is supported and otherwise fallback or disable the service?

**Comment by ealves-pt** [comment] 2016-02-16 15:57
At the moment that is not possible. That check is done using the $window service that is only available after the config phase.

Unfortunately this repo is not being maintained as actively as I would like so I have forked it and I'm rolling out my own version.

So far on my repo I have two version available. One with the old code, that I have converted to TypeScript, but transpiles to JS.

**Comment by g2graman** [comment] 2016-02-16 17:13
@ealves-pt 
I didn't know that this repository wasn't actively maintained. I suppose after enough time when your fork diverges from this you should consider breaking the fork off into its own repository.

For one, it's good to know what's supported before being locked to the storage type. I.e., it would be good to be able to know what is supported at the provider level.

I'm not sure if this is how you do it but I would go for using the Adapter pattern to abstract the storage mechanism to polymorphic storage types so that when I refer to the injected service ngWebStorageService, I am referring to my instance of the service based on the storage type. That would mean that for the most part the localStorage and the sessionStorage (for example) mechanisms would have the same functions and implement the same interface (which you can manipulate more visually with typescript's interfaces). You could go one step further and expose the storage adapter interface to allow other developers to extend the module by adding their own storage adapter. 

I am not sure if this repository handles it, but have you considered collision resolution? What happens if you try to put a key value pair with a key that already exists in storage?

I would also add an efficient 'has' function to the interface to be able to quickly if a specified key exists in the storage mechanism.

If I can help in any way, please let me know.

**Comment by ealves-pt** [comment] 2016-02-16 18:21
@g2graman 
Perhaps this repo will go back to life anytime soon, but in the meantime I need some features that it didn't have so I went ahead and I'm building my own. Eventually I will break the fork in the near future.

I'm doing almost everything you said on my new code. I have a `ngSessionWebStorageService` and a `ngLocalWebStorageService` and they share the exact same API. That way it will be easy to abstract further more if needed. (For now I have kept it simple). Yes, it is a good idea to expose the `AbstractStorageService` as you suggested. I will keep that in mind as an improvement for the future.

Regarding collision resolution, this repo will always override existing keys.

The `has` function might be a good addition to the `AbstractStorageService`.

I still have some functionalities missing in my code. For example:
* fallback mechanism when a specific storage is not available
* change key prefix at run time

And some other stuff I don't remember right now. So, PR are always welcome. :smile:

**Comment by grevory** [comment] 2016-02-16 21:59
I'm actually looking for help maintaining this repo. So many issues and
PRs. I am looking for Collaborators.


Greg

**Comment by ealves-pt** [comment] 2016-02-17 08:15
@grevory 

At the moment I have a PR, #279, open with small updates and fixes for minor issues.

If you want we can try to come up with a way to merge my fork into this repo. Even though I have migrated the entire code to TypeScript the API is still the same and all the tests are accepted.

Besides that, I'm rolling out my own version with some core changes and if you find it interesting we can also access the possibility to integrate them.

**Comment by g2graman** [comment] 2016-02-17 20:01
@grevory If possible, I would like to help maintain the repository as well by submitting my own PRs to have reviewed by other collaborators, reviewing other people's PR and approval. 

I would very much like to work with you, @ealves-pt 

Otherwise I'll stop adding to the current issue until I submit a PR to fix it.

**Comment by ealves-pt** [comment] 2016-02-17 20:50
Nice, for me it's perfect. :+1:

I suggest taking a look to all the PR open at the moment and also the issues to see where to start first. Regarding my fork of this repository I will create a discussion issue so we can decide if it makes sense, or not, some of the stuff that I did.

**Comment by grevory** [comment] 2016-02-17 20:57
Yea, there are so many PRs that they can't just be accepted. There will be a lot of conflicts to work through and I greatly appreciate the help guys.

**Comment by grevory** [comment] 2016-02-17 23:42
Thank you so much!

**Comment by ealves-pt** [comment] 2016-02-18 07:33
As you guys should have noticed I did some "spring cleaning" to the issues yesterday. Today I will go through the PR to see what is hanging around there. I will also create a new issue with a task list and mark it as RFC so we can discuss the next steps to take.

Regarding the subject of this issue I will mark it as a duplicate but I will leave it open for now.

Duplicate of #181

**Comment by KennedyIhe** [comment] 2016-02-18 19:38
I use this repository a lot in my applications and I'm surprised it is not maintained. I will like to help maintain it and add the needed features especially the ones discussed in the last few days.

**Comment by ealves-pt** [comment] 2016-02-18 21:04
Perfect :+1:

**Comment by ealves-pt** [comment] 2016-02-19 15:09
Let's continue this discussion on #151

**Closed by ealves-pt** 2016-02-19 15:09 UTC
Labels: duplicate, question
