### ISSUE TITLE
Allow creating multiple instances

### ISSUE THREAD

**Issue by m-j** [grevory/angular-local-storage#270] opened 2016-01-18 13:46 UTC
Restangular has similar thing. You can have your own instances of Restangular object one can be configured to hit /api onther one to hit /some-other-api.

It would be nice to have such feature here so you can use localStorage and sessionStorage simultaneously.

**Comment by JesLabs** [comment] 2016-01-19 13:33
:+1:

**Comment by ealves-pt** [comment] 2016-02-18 00:35
Duplicate of #181

**Comment by ealves-pt** [comment] 2016-02-19 15:09
Let's continue this discussion on #151

**Closed by ealves-pt** 2016-02-19 15:09 UTC
Labels: duplicate, enhancement
